sudo: required

language: cpp

matrix:
  include:
    - os: linux
      services: docker
      before_install: docker pull glportal/whale-gcc
      script:
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "cmake ./; make; make tests;"
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "./external/RadixEngine/tests/SystemGraphTest ./data"
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "./external/RadixEngine/tests/XmlReadingTest"
    - os: osx
      sudo: required
      osx_image: xcode8
      compiler: gcc
      git:
        submodules: false
      before_install:
        - brew update
        - brew install gcc
        - brew install assimp
        - brew install libepoxy
        - brew install sdl2
        - brew install sdl2_mixer
        - brew install bullet
        - brew install tinyxml2
        - brew install unittest-cpp
        - brew install freeimage
        - git submodule update --init --recursive
      before_script:
        - mkdir build && cd build
        - CC=gcc-6
        - CXXÇµ++-6
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install ..
        - make -j4

notifications:
#  irc: "chat.freenode.net#glportal"
