sudo: required

language: c++

matrix:
  include:
    - os: linux
      services: docker
      before_install: docker pull glportal/whale-gcc
      script:
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "cmake ./; make; make tests;"
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "./external/RadixEngine/tests/SystemGraphTest ./data"
        - docker run -it --rm -w /data -v $(pwd):/data glportal/whale-gcc bash -c "./external/RadixEngine/tests/XmlReadingTest"
    - os: osx
      sudo: required
      compiler:
        - gcc
        - clang

notifications:
#  irc: "chat.freenode.net#glportal"
